<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Permissoes
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim TreeNode1 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Clientes")
        Dim TreeNode2 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Região")
        Dim TreeNode3 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ver Limite de Crédito")
        Dim TreeNode4 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório Cliente")
        Dim TreeNode5 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Clientes Aniversariante")
        Dim TreeNode6 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Clientes", New System.Windows.Forms.TreeNode() {TreeNode1, TreeNode2, TreeNode3, TreeNode4, TreeNode5})
        Dim TreeNode7 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Cep")
        Dim TreeNode8 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Fornecedor")
        Dim TreeNode9 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório Fornecedor")
        Dim TreeNode10 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Fornecedores", New System.Windows.Forms.TreeNode() {TreeNode8, TreeNode9})
        Dim TreeNode11 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Produtos")
        Dim TreeNode12 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Produtos")
        Dim TreeNode13 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Produtos Inativos")
        Dim TreeNode14 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Estoque")
        Dim TreeNode15 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Atualizador de Estoque")
        Dim TreeNode16 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Saída de Produtos")
        Dim TreeNode17 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ajuste do Estoque")
        Dim TreeNode18 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Grupos")
        Dim TreeNode19 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Marcas")
        Dim TreeNode20 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Cor")
        Dim TreeNode21 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Localização")
        Dim TreeNode22 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios de Produtos")
        Dim TreeNode23 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Cadastro Gerais")
        Dim TreeNode24 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Saldo de Estoque")
        Dim TreeNode25 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Etiquetas de Produtos")
        Dim TreeNode26 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Gerar Etiquetas")
        Dim TreeNode27 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Retorno")
        Dim TreeNode28 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Produtos", New System.Windows.Forms.TreeNode() {TreeNode11, TreeNode12, TreeNode13, TreeNode14, TreeNode15, TreeNode16, TreeNode17, TreeNode18, TreeNode19, TreeNode20, TreeNode21, TreeNode22, TreeNode23, TreeNode24, TreeNode25, TreeNode26, TreeNode27})
        Dim TreeNode29 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Condição de Pagamento")
        Dim TreeNode30 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Tipo de Pagamento")
        Dim TreeNode31 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Anexar Cond. Pgto ao Tipo de Pgto")
        Dim TreeNode32 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Cfop")
        Dim TreeNode33 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro CFOP Entrada e Saída p/Importador")
        Dim TreeNode34 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro NCM")
        Dim TreeNode35 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Transportadora/Motorista")
        Dim TreeNode36 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastros Gerais", New System.Windows.Forms.TreeNode() {TreeNode29, TreeNode30, TreeNode31, TreeNode32, TreeNode33, TreeNode34, TreeNode35})
        Dim TreeNode37 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Empresa")
        Dim TreeNode38 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Contabilista")
        Dim TreeNode39 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Frete")
        Dim TreeNode40 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Geral", New System.Windows.Forms.TreeNode() {TreeNode6, TreeNode7, TreeNode10, TreeNode28, TreeNode36, TreeNode37, TreeNode38, TreeNode39})
        Dim TreeNode41 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Prorrogação contas a Receber")
        Dim TreeNode42 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alterar Local de Pagamento")
        Dim TreeNode43 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alterar Data de Vencimento")
        Dim TreeNode44 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alterar Conta Corrente")
        Dim TreeNode45 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Interno Receber", New System.Windows.Forms.TreeNode() {TreeNode41, TreeNode42, TreeNode43, TreeNode44})
        Dim TreeNode46 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta/Baixa de Contas a Receber", New System.Windows.Forms.TreeNode() {TreeNode45})
        Dim TreeNode47 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Baixa Recebimento em Lote")
        Dim TreeNode48 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Agrupar Recebimento")
        Dim TreeNode49 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("A Receber Avulso")
        Dim TreeNode50 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Contas a Receber")
        Dim TreeNode51 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Contas a Receber no Período e Valor")
        Dim TreeNode52 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("--------------------------------------")
        Dim TreeNode53 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Editar contas a Pagar")
        Dim TreeNode54 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Editar Parcelamento Contas a Pagar")
        Dim TreeNode55 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Interno Pagar", New System.Windows.Forms.TreeNode() {TreeNode53, TreeNode54})
        Dim TreeNode56 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta/Baixa de Contas a Pagar", New System.Windows.Forms.TreeNode() {TreeNode55})
        Dim TreeNode57 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Agrupar Pagamento")
        Dim TreeNode58 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de consta a Pagar")
        Dim TreeNode59 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("--------------------------------------")
        Dim TreeNode60 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Recibo Avulso")
        Dim TreeNode61 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Emitir Duplicata Avulso")
        Dim TreeNode62 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reimprimir Recibo Pagar e Receber")
        Dim TreeNode63 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("--------------------------------------")
        Dim TreeNode64 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Central de Cartão de Crédito")
        Dim TreeNode65 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("--------------------------------------")
        Dim TreeNode66 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Central de Boletos")
        Dim TreeNode67 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Pagar e Receber", New System.Windows.Forms.TreeNode() {TreeNode46, TreeNode47, TreeNode48, TreeNode49, TreeNode50, TreeNode51, TreeNode52, TreeNode56, TreeNode57, TreeNode58, TreeNode59, TreeNode60, TreeNode61, TreeNode62, TreeNode63, TreeNode64, TreeNode65, TreeNode66})
        Dim TreeNode68 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Senha desconto produto")
        Dim TreeNode69 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("NFe")
        Dim TreeNode70 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Locação", New System.Windows.Forms.TreeNode() {TreeNode68, TreeNode69})
        Dim TreeNode71 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cancelar Locação")
        Dim TreeNode72 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Orçamento")
        Dim TreeNode73 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Locação")
        Dim TreeNode74 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Compras")
        Dim TreeNode75 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios", New System.Windows.Forms.TreeNode() {TreeNode73, TreeNode74})
        Dim TreeNode76 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Documento de Entrada")
        Dim TreeNode77 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Nota Fiscal de Entrada")
        Dim TreeNode78 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entrada", New System.Windows.Forms.TreeNode() {TreeNode76, TreeNode77})
        Dim TreeNode79 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Movimento", New System.Windows.Forms.TreeNode() {TreeNode70, TreeNode71, TreeNode72, TreeNode75, TreeNode78})
        Dim TreeNode80 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ativar e Desativar Caixa")
        Dim TreeNode81 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Repasse Cheque Pré do Caixa")
        Dim TreeNode82 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Lançamentos Caixa")
        Dim TreeNode83 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Visualizador do Caixa", New System.Windows.Forms.TreeNode() {TreeNode81, TreeNode82})
        Dim TreeNode84 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Estorno Recebimento")
        Dim TreeNode85 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Estorno de Pagamento")
        Dim TreeNode86 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Caixa")
        Dim TreeNode87 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("-----------------------------------")
        Dim TreeNode88 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Movimentação Caixa/Banco")
        Dim TreeNode89 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Movimentação Compras")
        Dim TreeNode90 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Movimentação Centro de Custo")
        Dim TreeNode91 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Conferência", New System.Windows.Forms.TreeNode() {TreeNode88, TreeNode89, TreeNode90})
        Dim TreeNode92 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("-----------------------------------")
        Dim TreeNode93 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Contas de Receitas / Despesas")
        Dim TreeNode94 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Contas de Centro de Custo")
        Dim TreeNode95 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reclassificar Contas")
        Dim TreeNode96 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Verificador de Inconsistência")
        Dim TreeNode97 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Receitas e Despesas")
        Dim TreeNode98 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Centro de Custo")
        Dim TreeNode99 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios", New System.Windows.Forms.TreeNode() {TreeNode97, TreeNode98})
        Dim TreeNode100 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Bancos")
        Dim TreeNode101 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Conta Corrente")
        Dim TreeNode102 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Conta Corrente/Bancos", New System.Windows.Forms.TreeNode() {TreeNode100, TreeNode101})
        Dim TreeNode103 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Lançamento Banco")
        Dim TreeNode104 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Extrato Banco")
        Dim TreeNode105 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Compensar Cheque")
        Dim TreeNode106 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Central de Conta Corrente", New System.Windows.Forms.TreeNode() {TreeNode103, TreeNode104, TreeNode105})
        Dim TreeNode107 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cheque-Pré - Clientes")
        Dim TreeNode108 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cheque-Pré - Devolvidos")
        Dim TreeNode109 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Cheque Pré")
        Dim TreeNode110 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Contrato")
        Dim TreeNode111 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Caixa e Banco", New System.Windows.Forms.TreeNode() {TreeNode80, TreeNode83, TreeNode84, TreeNode85, TreeNode86, TreeNode87, TreeNode91, TreeNode92, TreeNode93, TreeNode94, TreeNode95, TreeNode96, TreeNode99, TreeNode102, TreeNode106, TreeNode107, TreeNode108, TreeNode109, TreeNode110})
        Dim TreeNode112 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Funcionários")
        Dim TreeNode113 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cartão de Funcionário")
        Dim TreeNode114 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Departamentos")
        Dim TreeNode115 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Profissão")
        Dim TreeNode116 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Funcionários")
        Dim TreeNode117 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Departamentos")
        Dim TreeNode118 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Profissão")
        Dim TreeNode119 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatorios de Funcionários", New System.Windows.Forms.TreeNode() {TreeNode116, TreeNode117, TreeNode118})
        Dim TreeNode120 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu RH", New System.Windows.Forms.TreeNode() {TreeNode112, TreeNode113, TreeNode114, TreeNode115, TreeNode119})
        Dim TreeNode121 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissões")
        Dim TreeNode122 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Gerenciador de Permissões")
        Dim TreeNode123 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Auditoria")
        Dim TreeNode124 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("UserSenha")
        Dim TreeNode125 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Caixa")
        Dim TreeNode126 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Caixas em Abertos")
        Dim TreeNode127 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Criar e Fechar Dia de Trabalho")
        Dim TreeNode128 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Configuração do Banco de Dados (Alternar)")
        Dim TreeNode129 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Atualizar Tabelas")
        Dim TreeNode130 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Sobre")
        Dim TreeNode131 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Configurações", New System.Windows.Forms.TreeNode() {TreeNode121, TreeNode122, TreeNode123, TreeNode124, TreeNode125, TreeNode126, TreeNode127, TreeNode128, TreeNode129, TreeNode130})
        Dim TreeNode132 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("----------------------------------")
        Dim TreeNode133 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Cliente")
        Dim TreeNode134 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta Produto")
        Dim TreeNode135 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Seletor")
        Dim TreeNode136 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Retorno")
        Dim TreeNode137 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Orçamento")
        Dim TreeNode138 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entregar")
        Dim TreeNode139 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Locação")
        Dim TreeNode140 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Inicira Caixa")
        Dim TreeNode141 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Vizualizar Caixa")
        Dim TreeNode142 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Recebimento")
        Dim TreeNode143 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pagamento")
        Dim TreeNode144 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Rápido", New System.Windows.Forms.TreeNode() {TreeNode133, TreeNode134, TreeNode135, TreeNode136, TreeNode137, TreeNode138, TreeNode139, TreeNode140, TreeNode141, TreeNode142, TreeNode143})
        Dim TreeNode145 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissão desc. Vendas")
        Dim TreeNode146 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Banco Compensar")
        Dim TreeNode147 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Codigo de Segurança")
        Dim TreeNode148 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Interno", New System.Windows.Forms.TreeNode() {TreeNode145, TreeNode146, TreeNode147})
        Dim TreeNode149 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Display")
        Dim TreeNode150 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Tools", New System.Windows.Forms.TreeNode() {TreeNode149})
        Dim TreeNode151 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Novo Agendamento")
        Dim TreeNode152 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Agenda de Compromissos", New System.Windows.Forms.TreeNode() {TreeNode151})
        Dim TreeNode153 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissão", New System.Windows.Forms.TreeNode() {TreeNode40, TreeNode67, TreeNode79, TreeNode111, TreeNode120, TreeNode131, TreeNode132, TreeNode144, TreeNode148, TreeNode150, TreeNode152})
        Me.PanelEx1 = New DevComponents.DotNetBar.PanelEx()
        Me.btCopiarDe = New DevComponents.DotNetBar.ButtonX()
        Me.btFechar = New DevComponents.DotNetBar.ButtonX()
        Me.ListaPermissao = New System.Windows.Forms.TreeView()
        Me.MenuAdicional = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.HelpProvider1 = New System.Windows.Forms.HelpProvider()
        Me.PanelEx1.SuspendLayout()
        Me.MenuAdicional.SuspendLayout()
        Me.SuspendLayout()
        '
        'PanelEx1
        '
        Me.PanelEx1.CanvasColor = System.Drawing.SystemColors.Control
        Me.PanelEx1.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled
        Me.PanelEx1.Controls.Add(Me.btCopiarDe)
        Me.PanelEx1.Controls.Add(Me.btFechar)
        Me.PanelEx1.Controls.Add(Me.ListaPermissao)
        Me.PanelEx1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.PanelEx1.Location = New System.Drawing.Point(0, 0)
        Me.PanelEx1.Name = "PanelEx1"
        Me.PanelEx1.Size = New System.Drawing.Size(481, 544)
        Me.PanelEx1.Style.Alignment = System.Drawing.StringAlignment.Center
        Me.PanelEx1.Style.BackColor1.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground
        Me.PanelEx1.Style.BackColor2.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2
        Me.PanelEx1.Style.Border = DevComponents.DotNetBar.eBorderType.SingleLine
        Me.PanelEx1.Style.BorderColor.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder
        Me.PanelEx1.Style.ForeColor.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText
        Me.PanelEx1.Style.GradientAngle = 90
        Me.PanelEx1.TabIndex = 1
        '
        'btCopiarDe
        '
        Me.btCopiarDe.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton
        Me.btCopiarDe.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground
        Me.btCopiarDe.Location = New System.Drawing.Point(12, 515)
        Me.btCopiarDe.Name = "btCopiarDe"
        Me.btCopiarDe.Size = New System.Drawing.Size(169, 23)
        Me.btCopiarDe.TabIndex = 16
        Me.btCopiarDe.Text = "Copiar permissões de Usuário"
        '
        'btFechar
        '
        Me.btFechar.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton
        Me.btFechar.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground
        Me.btFechar.Location = New System.Drawing.Point(396, 515)
        Me.btFechar.Name = "btFechar"
        Me.btFechar.Size = New System.Drawing.Size(75, 23)
        Me.btFechar.TabIndex = 15
        Me.btFechar.Text = "Fechar"
        '
        'ListaPermissao
        '
        Me.ListaPermissao.ContextMenuStrip = Me.MenuAdicional
        Me.ListaPermissao.Location = New System.Drawing.Point(12, 12)
        Me.ListaPermissao.Name = "ListaPermissao"
        TreeNode1.Name = "Clientes"
        TreeNode1.Tag = "S"
        TreeNode1.Text = "Cadastro Clientes"
        TreeNode1.ToolTipText = "Cadastro de Clientes"
        TreeNode2.Name = "Regiao"
        TreeNode2.Tag = "S"
        TreeNode2.Text = "Região"
        TreeNode2.ToolTipText = "Cadastro de Região"
        TreeNode3.Name = "ClientesVerSaldoCredito"
        TreeNode3.Tag = "S"
        TreeNode3.Text = "Ver Limite de Crédito"
        TreeNode3.ToolTipText = "Verifica o Limite para Faturamento"
        TreeNode4.Name = "RelClientes"
        TreeNode4.Tag = "S"
        TreeNode4.Text = "Relatório Cliente"
        TreeNode4.ToolTipText = "Relatório Cliente"
        TreeNode5.Name = "ClientesAniversariantes"
        TreeNode5.Tag = "S"
        TreeNode5.Text = "Clientes Aniversariante"
        TreeNode5.ToolTipText = "Clientes Aniversariante"
        TreeNode6.Name = "Node9"
        TreeNode6.Tag = "N"
        TreeNode6.Text = "Clientes"
        TreeNode7.Name = "CepLocalizar"
        TreeNode7.Tag = "S"
        TreeNode7.Text = "Consulta de Cep"
        TreeNode7.ToolTipText = "Consulta de Cep"
        TreeNode8.Name = "Fornecedor"
        TreeNode8.Tag = "S"
        TreeNode8.Text = "Cadastro Fornecedor"
        TreeNode8.ToolTipText = "Cadastro Fornecedor"
        TreeNode9.Name = "FornecedorRelatorio"
        TreeNode9.Tag = "S"
        TreeNode9.Text = "Relatório Fornecedor"
        TreeNode9.ToolTipText = "Relatório Fornecedor"
        TreeNode10.Name = "Node4"
        TreeNode10.Text = "Fornecedores"
        TreeNode11.Name = "Produtos"
        TreeNode11.Tag = "S"
        TreeNode11.Text = "Cadastro Produtos"
        TreeNode11.ToolTipText = "Cadastro Produtos"
        TreeNode12.Name = "ProcuraProduto"
        TreeNode12.Tag = "S"
        TreeNode12.Text = "Consulta de Produtos"
        TreeNode12.ToolTipText = "Consulta de Produtos"
        TreeNode13.Name = "ProdutosInativos"
        TreeNode13.Tag = "S"
        TreeNode13.Text = "Produtos Inativos"
        TreeNode13.ToolTipText = "Produtos Inativos"
        TreeNode14.Name = "ProdutoEstoqueConsulta"
        TreeNode14.Tag = "S"
        TreeNode14.Text = "Consulta de Estoque"
        TreeNode14.ToolTipText = "Consulta de Estoque"
        TreeNode15.Name = "ProdutoEstoqueAtualizar"
        TreeNode15.Tag = "S"
        TreeNode15.Text = "Atualizador de Estoque"
        TreeNode15.ToolTipText = "Atualizador de Estoque"
        TreeNode16.Name = "SaidaProdutos"
        TreeNode16.Tag = "S"
        TreeNode16.Text = "Saída de Produtos"
        TreeNode16.ToolTipText = "Saída de Produtos"
        TreeNode17.Name = "ProdutoEstoqueAjuste"
        TreeNode17.Tag = "S"
        TreeNode17.Text = "Ajuste do Estoque"
        TreeNode17.ToolTipText = "Ajuste do Estoque"
        TreeNode18.Name = "Grupos"
        TreeNode18.Tag = "S"
        TreeNode18.Text = "Cadastro de Grupos"
        TreeNode18.ToolTipText = "Cadastro de Grupos"
        TreeNode19.Name = "Marcas"
        TreeNode19.Tag = "S"
        TreeNode19.Text = "Cadastro de Marcas"
        TreeNode19.ToolTipText = "Cadastro de Marcas"
        TreeNode20.Name = "Cor"
        TreeNode20.Tag = "S"
        TreeNode20.Text = "Cadastro de Cor"
        TreeNode20.ToolTipText = "Cadastro de Cor"
        TreeNode21.Name = "ProdutoLocal"
        TreeNode21.Tag = "S"
        TreeNode21.Text = "Cadastro de Localização"
        TreeNode21.ToolTipText = "Cadastro de Localização"
        TreeNode22.Name = "ProdutoRelat"
        TreeNode22.Tag = "S"
        TreeNode22.Text = "Relatórios de Produtos"
        TreeNode22.ToolTipText = "Relatórios de Produtos"
        TreeNode23.Name = "CadGeraisRelat"
        TreeNode23.Tag = "S"
        TreeNode23.Text = "Relatório de Cadastro Gerais"
        TreeNode23.ToolTipText = "Relatório de Cadastro Gerais"
        TreeNode24.Name = "ProdutoSaldoEstoque"
        TreeNode24.Tag = "S"
        TreeNode24.Text = "Saldo de Estoque"
        TreeNode24.ToolTipText = "Saldo de Estoque"
        TreeNode25.Name = "ProdutoEtiquetas"
        TreeNode25.Tag = "S"
        TreeNode25.Text = "Etiquetas de Produtos"
        TreeNode25.ToolTipText = "Etiquetas de Produtos"
        TreeNode26.Name = "ProdutoGerarEtiqueta"
        TreeNode26.Tag = "S"
        TreeNode26.Text = "Gerar Etiquetas"
        TreeNode26.ToolTipText = "Gerar Etiquetas"
        TreeNode27.Name = "RetornoLocacao"
        TreeNode27.Tag = "S"
        TreeNode27.Text = "Retorno"
        TreeNode27.ToolTipText = "Retorno"
        TreeNode28.Name = "Node7"
        TreeNode28.Text = "Produtos"
        TreeNode29.Name = "FormaPgto"
        TreeNode29.Tag = "S"
        TreeNode29.Text = "Condição de Pagamento"
        TreeNode29.ToolTipText = "Condição de Pagamento"
        TreeNode30.Name = "TipoPgto"
        TreeNode30.Tag = "S"
        TreeNode30.Text = "Cadastro de Tipo de Pagamento"
        TreeNode30.ToolTipText = "Cadastro de Tipo de Pagamento"
        TreeNode31.Name = "TipoFormaPgto"
        TreeNode31.Tag = "S"
        TreeNode31.Text = "Anexar Cond. Pgto ao Tipo de Pgto"
        TreeNode31.ToolTipText = "Anexar Cond. Pgto ao Tipo de Pgto"
        TreeNode32.Name = "Cfop"
        TreeNode32.Tag = "S"
        TreeNode32.Text = "Cadastro de Cfop"
        TreeNode32.ToolTipText = "Cadastro de Cfop"
        TreeNode33.Name = "CFOPse"
        TreeNode33.Tag = "S"
        TreeNode33.Text = "Cadastro CFOP Entrada e Saída p/Importador"
        TreeNode33.ToolTipText = "Cadastro CFOP Entrada e Saída p/Importador"
        TreeNode34.Name = "Ncm"
        TreeNode34.Tag = "S"
        TreeNode34.Text = "Cadastro NCM"
        TreeNode34.ToolTipText = "Cadastro NCM"
        TreeNode35.Name = "Transportadora"
        TreeNode35.Tag = "S"
        TreeNode35.Text = "Cadastro de Transportadora/Motorista"
        TreeNode35.ToolTipText = "Cadastro de Transportadora/Motorista"
        TreeNode36.Name = "Node28"
        TreeNode36.Text = "Cadastros Gerais"
        TreeNode37.Name = "Empresa"
        TreeNode37.Tag = "S"
        TreeNode37.Text = "Empresa"
        TreeNode37.ToolTipText = "Cadastro da Empresa"
        TreeNode38.Name = "Contabilista"
        TreeNode38.Tag = "S"
        TreeNode38.Text = "Contabilista"
        TreeNode38.ToolTipText = "Contabilista"
        TreeNode39.Name = "Frete"
        TreeNode39.Tag = "S"
        TreeNode39.Text = "Frete"
        TreeNode39.ToolTipText = "Frete"
        TreeNode40.Name = "Node3"
        TreeNode40.Tag = "N"
        TreeNode40.Text = "Menu Geral"
        TreeNode41.Name = "ReceberProrrogação"
        TreeNode41.Tag = "S"
        TreeNode41.Text = "Prorrogação contas a Receber"
        TreeNode41.ToolTipText = "Prorrogação contas a Receber"
        TreeNode42.Name = "ReceberAlterarLocalPagamento"
        TreeNode42.Tag = "S"
        TreeNode42.Text = "Alterar Local de Pagamento"
        TreeNode42.ToolTipText = "Alterar Local de Pagamento"
        TreeNode43.Name = "ReceberAlterarVencimento"
        TreeNode43.Tag = "S"
        TreeNode43.Text = "Alterar Data de Vencimento"
        TreeNode43.ToolTipText = "Alterar Data de Vencimento"
        TreeNode44.Name = "BoletoIndicarConta"
        TreeNode44.Tag = "S"
        TreeNode44.Text = "Alterar Conta Corrente"
        TreeNode44.ToolTipText = "Alterar Conta Corrente"
        TreeNode45.Name = "Node11"
        TreeNode45.Text = "Menu Interno Receber"
        TreeNode45.ToolTipText = "Menu Interno Receber"
        TreeNode46.Name = "Receber"
        TreeNode46.Tag = "S"
        TreeNode46.Text = "Consulta/Baixa de Contas a Receber"
        TreeNode46.ToolTipText = "Consulta/Baixa de Contas a Receber"
        TreeNode47.Name = "ReceberBaixaLote"
        TreeNode47.Tag = "S"
        TreeNode47.Text = "Baixa Recebimento em Lote"
        TreeNode47.ToolTipText = "Baixa Recebimento em Lote"
        TreeNode48.Name = "ReceberAgrupar"
        TreeNode48.Tag = "S"
        TreeNode48.Text = "Agrupar Recebimento"
        TreeNode48.ToolTipText = "Agrupar Recebimento"
        TreeNode49.Name = "ReceberAvulso"
        TreeNode49.Tag = "S"
        TreeNode49.Text = "A Receber Avulso"
        TreeNode49.ToolTipText = "A Receber Avulso"
        TreeNode50.Name = "ReceberRelat"
        TreeNode50.Tag = "S"
        TreeNode50.Text = "Relatório de Contas a Receber"
        TreeNode50.ToolTipText = "Relatório de Contas a Receber"
        TreeNode51.Name = "ReceberRelatPeriodoValor"
        TreeNode51.Tag = "S"
        TreeNode51.Text = "Contas a Receber no Período e Valor"
        TreeNode51.ToolTipText = "Contas a Receber no Período e Valor"
        TreeNode52.Name = "Node3"
        TreeNode52.Text = "--------------------------------------"
        TreeNode52.ToolTipText = "--------------------------------------"
        TreeNode53.Name = "PagarEditar"
        TreeNode53.Tag = "S"
        TreeNode53.Text = "Editar contas a Pagar"
        TreeNode53.ToolTipText = "Editar contas a Pagar"
        TreeNode54.Name = "pagarparcelamentos"
        TreeNode54.Tag = "S"
        TreeNode54.Text = "Editar Parcelamento Contas a Pagar"
        TreeNode54.ToolTipText = "Editar Parcelamento Contas a Pagar"
        TreeNode55.Name = "Node7"
        TreeNode55.Text = "Menu Interno Pagar"
        TreeNode55.ToolTipText = "Menu Interno Pagar"
        TreeNode56.Name = "Pagar"
        TreeNode56.Tag = "S"
        TreeNode56.Text = "Consulta/Baixa de Contas a Pagar"
        TreeNode56.ToolTipText = "Consulta/Baixa de Contas a Pagar"
        TreeNode57.Name = "PagarAgrupar"
        TreeNode57.Tag = "S"
        TreeNode57.Text = "Agrupar Pagamento"
        TreeNode57.ToolTipText = "Agrupar Pagamento"
        TreeNode58.Name = "PagarRelat"
        TreeNode58.Tag = "S"
        TreeNode58.Text = "Relatório de consta a Pagar"
        TreeNode58.ToolTipText = "Relatório de consta a Pagar"
        TreeNode59.Name = "Node5"
        TreeNode59.Text = "--------------------------------------"
        TreeNode59.ToolTipText = "--------------------------------------"
        TreeNode60.Name = "ReciboAvulso"
        TreeNode60.Tag = "S"
        TreeNode60.Text = "Recibo Avulso"
        TreeNode60.ToolTipText = "Recibo Avulso"
        TreeNode61.Name = "DuplicataAvulso"
        TreeNode61.Tag = "S"
        TreeNode61.Text = "Emitir Duplicata Avulso"
        TreeNode61.ToolTipText = "Emitir Duplicata Avulso"
        TreeNode62.Name = "ReimpressaoReciboPagarReceber"
        TreeNode62.Tag = "S"
        TreeNode62.Text = "Reimprimir Recibo Pagar e Receber"
        TreeNode62.ToolTipText = "Reimprimir Recibo Pagar e Receber"
        TreeNode63.Name = "Node6"
        TreeNode63.Text = "--------------------------------------"
        TreeNode63.ToolTipText = "--------------------------------------"
        TreeNode64.Name = "CartaoCreditoMenu"
        TreeNode64.Tag = "S"
        TreeNode64.Text = "Central de Cartão de Crédito"
        TreeNode64.ToolTipText = "Central de Cartão de Crédito"
        TreeNode65.Name = "Node8"
        TreeNode65.Text = "--------------------------------------"
        TreeNode65.ToolTipText = "--------------------------------------"
        TreeNode66.Name = "GeradorBoletos"
        TreeNode66.Tag = "S"
        TreeNode66.Text = "Central de Boletos"
        TreeNode66.ToolTipText = "Central de Boletos"
        TreeNode67.Name = "Node4"
        TreeNode67.Tag = "N"
        TreeNode67.Text = "Menu Pagar e Receber"
        TreeNode68.Name = "PedidoVendaSenhaItem"
        TreeNode68.Tag = "S"
        TreeNode68.Text = "Senha desconto produto"
        TreeNode68.ToolTipText = "Senha desconto produto"
        TreeNode69.Name = "NFeValidarDados"
        TreeNode69.Tag = "S"
        TreeNode69.Text = "NFe"
        TreeNode69.ToolTipText = "NFe"
        TreeNode70.Name = "PedidoVenda"
        TreeNode70.Tag = "S"
        TreeNode70.Text = "Locação"
        TreeNode70.ToolTipText = "Locação"
        TreeNode71.Name = "LocacaoCancelar"
        TreeNode71.Tag = "S"
        TreeNode71.Text = "Cancelar Locação"
        TreeNode71.ToolTipText = "Cancelar Locação"
        TreeNode72.Name = "OrdemEntrega"
        TreeNode72.Tag = "S"
        TreeNode72.Text = "Orçamento"
        TreeNode72.ToolTipText = "Orçamento"
        TreeNode73.Name = "LocacaoRelatorios"
        TreeNode73.Tag = "S"
        TreeNode73.Text = "Locação"
        TreeNode73.ToolTipText = "Locação"
        TreeNode74.Name = "ComprasRelat"
        TreeNode74.Tag = "S"
        TreeNode74.Text = "Compras"
        TreeNode74.ToolTipText = "Compras"
        TreeNode75.Name = "Node59"
        TreeNode75.Text = "Relatórios"
        TreeNode75.ToolTipText = "Relatórios"
        TreeNode76.Name = "DocumentoEntrada"
        TreeNode76.Tag = "S"
        TreeNode76.Text = "Documento de Entrada"
        TreeNode76.ToolTipText = "Documento de Entrada"
        TreeNode77.Name = "Compra"
        TreeNode77.Tag = "S"
        TreeNode77.Text = "Nota Fiscal de Entrada"
        TreeNode77.ToolTipText = "Nota Fiscal de Entrada"
        TreeNode78.Name = "Node67"
        TreeNode78.Text = "Entrada"
        TreeNode79.Name = "Node5"
        TreeNode79.Tag = "N"
        TreeNode79.Text = "Menu Movimento"
        TreeNode80.Name = "CaixaAtivarDesativar"
        TreeNode80.Tag = "S"
        TreeNode80.Text = "Ativar e Desativar Caixa"
        TreeNode80.ToolTipText = "Ativar e Desativar Caixa"
        TreeNode81.Name = "CaixaRepasseCheque"
        TreeNode81.Tag = "S"
        TreeNode81.Text = "Repasse Cheque Pré do Caixa"
        TreeNode81.ToolTipText = "Repasse Cheque Pré do Caixa"
        TreeNode82.Name = "CaixaLançamentos"
        TreeNode82.Tag = "S"
        TreeNode82.Text = "Lançamentos Caixa"
        TreeNode82.ToolTipText = "Lançamentos Caixa"
        TreeNode83.Name = "Caixa"
        TreeNode83.Tag = "S"
        TreeNode83.Text = "Visualizador do Caixa"
        TreeNode83.ToolTipText = "Visualizador do Caixa"
        TreeNode84.Name = "RecebidaVoltar"
        TreeNode84.Tag = "S"
        TreeNode84.Text = "Estorno Recebimento"
        TreeNode84.ToolTipText = "Estorno Recebimento"
        TreeNode85.Name = "PagasVoltar"
        TreeNode85.Tag = "S"
        TreeNode85.Text = "Estorno de Pagamento"
        TreeNode85.ToolTipText = "Estorno de Pagamento"
        TreeNode86.Name = "CaixaRelat"
        TreeNode86.Tag = "S"
        TreeNode86.Text = "Relatórios Caixa"
        TreeNode86.ToolTipText = "Relatórios Caixa"
        TreeNode87.Name = "Node0"
        TreeNode87.Text = "-----------------------------------"
        TreeNode87.ToolTipText = "-----------------------------------"
        TreeNode88.Name = "DiaConferenciaRelat"
        TreeNode88.Tag = "S"
        TreeNode88.Text = "Movimentação Caixa/Banco"
        TreeNode88.ToolTipText = "Movimentação Caixa/Banco"
        TreeNode89.Name = "CompraDiaConferenciaRelat"
        TreeNode89.Tag = "S"
        TreeNode89.Text = "Movimentação Compras"
        TreeNode89.ToolTipText = "Movimentação Compras"
        TreeNode90.Name = "CentroCustoDiaConferenciaRelat"
        TreeNode90.Tag = "S"
        TreeNode90.Text = "Movimentação Centro de Custo"
        TreeNode90.ToolTipText = "Movimentação Centro de Custo"
        TreeNode91.Name = "Node1"
        TreeNode91.Text = "Conferência"
        TreeNode91.ToolTipText = "Conferência"
        TreeNode92.Name = "Node2"
        TreeNode92.Text = "-----------------------------------"
        TreeNode92.ToolTipText = "-----------------------------------"
        TreeNode93.Name = "BalanceteCadastro"
        TreeNode93.Tag = "S"
        TreeNode93.Text = "Cadastro de Contas de Receitas / Despesas"
        TreeNode93.ToolTipText = "Cadastro de Conta Balancete"
        TreeNode94.Name = "CentroCustoNew"
        TreeNode94.Tag = "S"
        TreeNode94.Text = "Cadastro de Contas de Centro de Custo"
        TreeNode94.ToolTipText = "Cadastro de Contas de Centro de Custo"
        TreeNode95.Name = "BalanceteEdit"
        TreeNode95.Tag = "S"
        TreeNode95.Text = "Reclassificar Contas"
        TreeNode95.ToolTipText = "Reclassificar Contas"
        TreeNode96.Name = "BalanceteCentroCustoErro"
        TreeNode96.Tag = "S"
        TreeNode96.Text = "Verificador de Inconsistência"
        TreeNode96.ToolTipText = "Verificador de Inconsistência"
        TreeNode97.Name = "BalanceteRelat"
        TreeNode97.Tag = "S"
        TreeNode97.Text = "Relatórios Receitas e Despesas"
        TreeNode97.ToolTipText = "Relatórios Receitas e Despesas"
        TreeNode98.Name = "CentroCustoNewRelat"
        TreeNode98.Tag = "S"
        TreeNode98.Text = "Relatórios Centro de Custo"
        TreeNode98.ToolTipText = "Relatórios Centro de Custo"
        TreeNode99.Name = "MostrarContasInativas"
        TreeNode99.Tag = "S"
        TreeNode99.Text = "Relatórios"
        TreeNode99.ToolTipText = "Relatórios"
        TreeNode100.Name = "BancosCad"
        TreeNode100.Tag = "S"
        TreeNode100.Text = "Cadastro de Bancos"
        TreeNode100.ToolTipText = "Cadastro de Bancos"
        TreeNode101.Name = "BancosContaCorrente"
        TreeNode101.Tag = "S"
        TreeNode101.Text = "Cadastro Conta Corrente"
        TreeNode101.ToolTipText = "Cadastro Conta Corrente"
        TreeNode102.Name = "Node12"
        TreeNode102.Text = "Conta Corrente/Bancos"
        TreeNode103.Name = "BancoLançamento"
        TreeNode103.Tag = "S"
        TreeNode103.Text = "Lançamento Banco"
        TreeNode103.ToolTipText = "Lançamento Banco"
        TreeNode104.Name = "BancoExtrato"
        TreeNode104.Tag = "S"
        TreeNode104.Text = "Extrato Banco"
        TreeNode104.ToolTipText = "Extrato Banco"
        TreeNode105.Name = "BancoCompensar"
        TreeNode105.Tag = "S"
        TreeNode105.Text = "Compensar Cheque"
        TreeNode105.ToolTipText = "Compensar Cheque"
        TreeNode106.Name = "BancoVisualizador"
        TreeNode106.Tag = "S"
        TreeNode106.Text = "Central de Conta Corrente"
        TreeNode106.ToolTipText = "Central de Conta Corrente"
        TreeNode107.Name = "ChequePreClientes"
        TreeNode107.Tag = "S"
        TreeNode107.Text = "Cheque-Pré - Clientes"
        TreeNode107.ToolTipText = "Cheque-Pré - Clientes"
        TreeNode108.Name = "Chequepredevolver"
        TreeNode108.Tag = "S"
        TreeNode108.Text = "Cheque-Pré - Devolvidos"
        TreeNode108.ToolTipText = "Cheque-Pré - Devolvidos"
        TreeNode109.Name = "ChequePreRelat"
        TreeNode109.Tag = "S"
        TreeNode109.Text = "Relatórios Cheque Pré"
        TreeNode109.ToolTipText = "Relatórios Cheque Pré"
        TreeNode110.Name = "Contrato"
        TreeNode110.Tag = "S"
        TreeNode110.Text = "Contrato"
        TreeNode110.ToolTipText = "Contrato"
        TreeNode111.Name = "Node6"
        TreeNode111.Tag = "N"
        TreeNode111.Text = "Menu Caixa e Banco"
        TreeNode112.Name = "Funcionarios"
        TreeNode112.Tag = "S"
        TreeNode112.Text = "Funcionários"
        TreeNode112.ToolTipText = "Funcionários"
        TreeNode113.Name = "FuncionarioCartao"
        TreeNode113.Tag = "S"
        TreeNode113.Text = "Cartão de Funcionário"
        TreeNode113.ToolTipText = "Cartão de Funcionário"
        TreeNode114.Name = "Departamentos"
        TreeNode114.Tag = "S"
        TreeNode114.Text = "Departamentos"
        TreeNode114.ToolTipText = "Departamentos"
        TreeNode115.Name = "Profissao"
        TreeNode115.Tag = "S"
        TreeNode115.Text = "Cadastro de Profissão"
        TreeNode115.ToolTipText = "Cadastro de Profissão"
        TreeNode116.Name = "FuncionariosRelat"
        TreeNode116.Tag = "S"
        TreeNode116.Text = "Funcionários"
        TreeNode116.ToolTipText = "Relatório de Funcionários"
        TreeNode117.Name = "RelDepartamentos"
        TreeNode117.Tag = "S"
        TreeNode117.Text = "Departamentos"
        TreeNode117.ToolTipText = "Relatório de Departamentos"
        TreeNode118.Name = "RelProfissão"
        TreeNode118.Tag = "S"
        TreeNode118.Text = "Profissão"
        TreeNode118.ToolTipText = "Relatório de Profissão"
        TreeNode119.Name = "Node0"
        TreeNode119.Text = "Relatorios de Funcionários"
        TreeNode120.Name = "Node7"
        TreeNode120.Tag = "N"
        TreeNode120.Text = "Menu RH"
        TreeNode121.Name = "Permissoes"
        TreeNode121.Tag = "S"
        TreeNode121.Text = "Permissões"
        TreeNode121.ToolTipText = "Cadastro de Permissões"
        TreeNode122.Name = "PermissaoGetPost"
        TreeNode122.Tag = "S"
        TreeNode122.Text = "Gerenciador de Permissões"
        TreeNode122.ToolTipText = "Gerenciador de Permissões"
        TreeNode123.Name = "Auditor"
        TreeNode123.Tag = "S"
        TreeNode123.Text = "Auditoria"
        TreeNode123.ToolTipText = "Auditoria"
        TreeNode124.Name = "UserSenha"
        TreeNode124.Tag = "S"
        TreeNode124.Text = "UserSenha"
        TreeNode124.ToolTipText = "Cadastro de Senha de Usuário"
        TreeNode125.Name = "CaixaCadastro"
        TreeNode125.Tag = "S"
        TreeNode125.Text = "Cadastro de Caixa"
        TreeNode125.ToolTipText = "Cadastro de Caixa"
        TreeNode126.Name = "CaixasAbertos"
        TreeNode126.Tag = "S"
        TreeNode126.Text = "Caixas em Abertos"
        TreeNode126.ToolTipText = "Caixas em Abertos"
        TreeNode127.Name = "DiaAbrirFechar"
        TreeNode127.Tag = "S"
        TreeNode127.Text = "Criar e Fechar Dia de Trabalho"
        TreeNode127.ToolTipText = "Criar e Fechar Dia de Trabalho"
        TreeNode128.Name = "Cfg"
        TreeNode128.Tag = "S"
        TreeNode128.Text = "Configuração do Banco de Dados (Alternar)"
        TreeNode128.ToolTipText = "Configuração do Banco de Dados (Alternar)"
        TreeNode129.Name = "AtTabelas"
        TreeNode129.Tag = "S"
        TreeNode129.Text = "Atualizar Tabelas"
        TreeNode129.ToolTipText = "Atualizar Tabelas"
        TreeNode130.Name = "Sobre"
        TreeNode130.Text = "Sobre"
        TreeNode130.ToolTipText = "Sobre"
        TreeNode131.Name = "Node8"
        TreeNode131.Tag = "N"
        TreeNode131.Text = "Menu Configurações"
        TreeNode132.Name = "Node0"
        TreeNode132.Text = "----------------------------------"
        TreeNode133.Name = "ClientesProcura"
        TreeNode133.Tag = "S"
        TreeNode133.Text = "Consulta de Cliente"
        TreeNode133.ToolTipText = "Consulta de Cliente"
        TreeNode134.Name = "ProcuraProduto"
        TreeNode134.Tag = "S"
        TreeNode134.Text = "Consulta Produto"
        TreeNode134.ToolTipText = "Consulta Produto"
        TreeNode135.Name = "LocacaoSeletor"
        TreeNode135.Tag = "S"
        TreeNode135.Text = "Seletor"
        TreeNode135.ToolTipText = "Seletor"
        TreeNode136.Name = "Devolucao"
        TreeNode136.Tag = "S"
        TreeNode136.Text = "Retorno"
        TreeNode136.ToolTipText = "Retorno"
        TreeNode137.Name = "LocacaoOrcamentoProcurar"
        TreeNode137.Tag = "S"
        TreeNode137.Text = "Orçamento"
        TreeNode137.ToolTipText = "Orçamento"
        TreeNode138.Name = "LocacaoEntregar"
        TreeNode138.Tag = "S"
        TreeNode138.Text = "Entregar"
        TreeNode138.ToolTipText = "Entregar"
        TreeNode139.Name = "Locacao"
        TreeNode139.Tag = "S"
        TreeNode139.Text = "Locação"
        TreeNode139.ToolTipText = "Locação"
        TreeNode140.Name = "CaixaAtivarDesativar"
        TreeNode140.Tag = "S"
        TreeNode140.Text = "Inicira Caixa"
        TreeNode140.ToolTipText = "Inicira Caixa"
        TreeNode141.Name = "Caixa"
        TreeNode141.Tag = "S"
        TreeNode141.Text = "Vizualizar Caixa"
        TreeNode141.ToolTipText = "Vizualizar Caixa"
        TreeNode142.Name = "Receber"
        TreeNode142.Tag = "S"
        TreeNode142.Text = "Recebimento"
        TreeNode142.ToolTipText = "Recebimento"
        TreeNode143.Name = "Pagar"
        TreeNode143.Tag = "S"
        TreeNode143.Text = "Pagamento"
        TreeNode143.ToolTipText = "Pagamento"
        TreeNode144.Name = "Node1"
        TreeNode144.Text = "Menu Rápido"
        TreeNode145.Name = "PedidoVendaSenhaItem"
        TreeNode145.Tag = "S"
        TreeNode145.Text = "Permissão desc. Vendas"
        TreeNode145.ToolTipText = "Permissão desc. Vendas"
        TreeNode146.Name = "BancoCompensar"
        TreeNode146.Tag = "S"
        TreeNode146.Text = "Banco Compensar"
        TreeNode146.ToolTipText = "Banco Compensar"
        TreeNode147.Name = "CodigoSegurancaInformar"
        TreeNode147.Tag = "S"
        TreeNode147.Text = "Codigo de Segurança"
        TreeNode147.ToolTipText = "Informar código de Segurança"
        TreeNode148.Name = "Menu Interno"
        TreeNode148.Text = "Menu Interno"
        TreeNode149.Name = "MenuDisplay"
        TreeNode149.Tag = "S"
        TreeNode149.Text = "Menu Display"
        TreeNode149.ToolTipText = "Menu Display"
        TreeNode150.Name = "Tools"
        TreeNode150.Text = "Tools"
        TreeNode150.ToolTipText = "Tools"
        TreeNode151.Name = "AddCompromisso"
        TreeNode151.Tag = "S"
        TreeNode151.Text = "Novo Agendamento"
        TreeNode151.ToolTipText = "Novo Agendamento"
        TreeNode152.Name = "Node5"
        TreeNode152.Text = "Agenda de Compromissos"
        TreeNode153.Name = "Permissao"
        TreeNode153.Text = "Permissão"
        Me.ListaPermissao.Nodes.AddRange(New System.Windows.Forms.TreeNode() {TreeNode153})
        Me.ListaPermissao.Size = New System.Drawing.Size(459, 497)
        Me.ListaPermissao.TabIndex = 0
        '
        'MenuAdicional
        '
        Me.MenuAdicional.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem})
        Me.MenuAdicional.Name = "MenuAdicional"
        Me.MenuAdicional.Size = New System.Drawing.Size(249, 26)
        '
        'AddPermissãoGrupoDeUsuárioToolStripMenuItem
        '
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Name = "AddPermissãoGrupoDeUsuárioToolStripMenuItem"
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Size = New System.Drawing.Size(248, 22)
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Text = "Add Permissão Grupo de Usuário"
        '
        'HelpProvider1
        '
        Me.HelpProvider1.HelpNamespace = "C:\UpSistemas\Help\dblsistemas.chm"
        '
        'Permissoes
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(481, 544)
        Me.ControlBox = False
        Me.Controls.Add(Me.PanelEx1)
        Me.Font = New System.Drawing.Font("Comic Sans MS", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow
        Me.HelpProvider1.SetHelpNavigator(Me, System.Windows.Forms.HelpNavigator.KeywordIndex)
        Me.Name = "Permissoes"
        Me.HelpProvider1.SetShowHelp(Me, True)
        Me.ShowInTaskbar = False
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Permissões - T191"
        Me.PanelEx1.ResumeLayout(False)
        Me.MenuAdicional.ResumeLayout(False)
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents PanelEx1 As DevComponents.DotNetBar.PanelEx
    Friend WithEvents ListaPermissao As System.Windows.Forms.TreeView
    Friend WithEvents btFechar As DevComponents.DotNetBar.ButtonX
    Friend WithEvents MenuAdicional As System.Windows.Forms.ContextMenuStrip
    Friend WithEvents AddPermissãoGrupoDeUsuárioToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents HelpProvider1 As System.Windows.Forms.HelpProvider
    Friend WithEvents btCopiarDe As DevComponents.DotNetBar.ButtonX
End Class
